fix: Update SSH connection command in CI/CD pipeline for EC2 deployment

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -61,7 +61,7 @@ jobs:
 
       - name: Update security group
         run: |
-          aws ec2 authorize-security-group-ingress --group-id sg-09f3ce907a9d2f0ca --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.value }}/32
+          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.value }}/32
 
       - name: Deploy to EC2
         env:
@@ -69,14 +69,22 @@ jobs:
           EC2_HOST: ${{ secrets.EC2_HOST }}
           EC2_USER: ${{ secrets.EC2_USER }}
         run: |
-          echo "${EC2_SSH_PRIVATE_KEY}" > private_key.pem
-          chmod 600 private_key.pem
-          ssh -t -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
-          set -e  # エラーが発生した場合、スクリプトを終了
-          echo "Changing directory to app"
-          cd /LessonBoard || { echo "Failed to cd"; exit 1; }
-          echo "Pulling latest code"
-          git pull origin HEAD || { echo "Failed to pull code"; exit 1; }
-          echo "Starting Docker containers"
-          docker-compose -f docker-compose.prod.yml up -d --build || { echo "Failed to start containers"; exit 1; }
-          EOF
+          # echo "${EC2_SSH_PRIVATE_KEY}" > private_key.pem
+          # chmod 600 private_key.pem
+          # ssh -t -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
+          # set -e  # エラーが発生した場合、スクリプトを終了
+          # echo "Changing directory to app"
+          # cd /LessonBoard || { echo "Failed to cd"; exit 1; }
+          # echo "Pulling latest code"
+          # git pull origin HEAD || { echo "Failed to pull code"; exit 1; }
+          # echo "Starting Docker containers"
+          # docker-compose -f docker-compose.prod.yml up -d --build || { echo "Failed to start containers"; exit 1; }
+          # EOF
+
+         # SSH接続して、git pullする
+         echo "${{ EC2_SSH_PRIVATE_KEY }}" > private_key
+         chmod 600 private_key
+         ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -i private_key "cd /LessonBoard && git pull origin HEAD"
+
+         # SSHのセキュリティグループを閉じる
+         aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
