feat/test: Update error handling for Remove IP from EC2 security group step and test with intentional error

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -81,6 +81,8 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           script: |
+            echo "Forcing an error"
+            exit 1
             cd ~/LessonBoard
             git fetch origin
             echo "Fetching branches from origin..."
