feat: Improve CI/CD workflow in cicd.yml again

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -70,7 +70,7 @@ jobs:
           ssh -t -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
           set -e  # エラーが発生した場合、スクリプトを終了
           echo "Changing directory to app"
-          cd /lesson_board || { echo "Failed to cd"; exit 1; }
+          cd /LessonBoard || { echo "Failed to cd"; exit 1; }
           echo "Pulling latest code"
           git pull origin HEAD || { echo "Failed to pull code"; exit 1; }
           echo "Starting Docker containers"
